export const blogPosts = [
  {
    title: "5 Costly Signboard Mistakes Nagpur Businesses Make",
    category: "Business Advice",
    excerpt: "Is your signboard hurting your business? Discover the 5 most common and costly signboard mistakes.",
    date: "March 2025",
    slug: "/signboard-mistakes-nagpur-businesses",
    image: "/blog/5 Costly Signboard Mistakes Nagpur Businesses Make — And How to Avoid Every One.png",
  },
  {
    title: "ACP vs Acrylic vs Flex — Which Survives Nagpur's Weather?",
    category: "Materials",
    excerpt: "Nagpur is one of India's hottest cities. The signboard material you choose will either survive this or won't.",
    date: "March 2025",
    slug: "/acp-vs-acrylic-vs-flex-signboard-nagpur",
    image: "/blog/ACP vs Acrylic vs Flex — Which Signboard Material Survives Nagpur's Extreme Weather.png",
  },
  {
    title: "Best Signboard Ideas for Restaurants & Cafes in Nagpur",
    category: "Food & Beverage",
    excerpt: "The right signage can fill tables. Here's exactly what works for Nagpur's competitive food scene.",
    date: "March 2025",
    slug: "/restaurant-cafe-signboard-ideas-nagpur",
    image: "/blog/Best Signboard Ideas for Restaurants, Cafes & Hotels in Nagpur.png",
  },
  {
    title: "NMC Signboard Rules Nagpur 2025 — Essential Guide",
    category: "Legal Guide",
    excerpt: "NMC can fine and forcibly remove unauthorised signboards. Understand the permission process and rules.",
    date: "March 2025",
    slug: "/nmc-signboard-rules-nagpur-2025",
    image: "/blog/NMC Signboard Rules Nagpur 2025 — What Every Shop Owner Must Know Before Installing.png",
  },
  {
    title: "Golden Acrylic vs Stainless Steel Letters in Nagpur",
    category: "Luxury Signage",
    excerpt: "If your business needs to communicate exclusivity, the choice of material has real brand consequences.",
    date: "March 2025",
    slug: "/golden-acrylic-vs-ss-letters-nagpur",
    image: "/blog/Golden Acrylic Letters vs Stainless Steel Letters — Which Signals Luxury for Your Nagpur Business.png",
  },
  {
    title: "ACP Elevation Cladding Nagpur — Architects Guide",
    category: "Architecture",
    excerpt: "Complete guide on ACP elevation work — types of ACP panels, design options, and costs.",
    date: "March 2025",
    slug: "/acp-elevation-cladding-nagpur-guide",
    image: "/blog/ACP Elevation Cladding in Nagpur — A Complete Guide for Building Owners & Architects.png",
  },
  {
    title: "Best Signboard Makers on Wardha Road Nagpur",
    category: "Local Spotlight",
    excerpt: "Wardha Road is growing fast. If you're opening there, your signboard needs to stand out.",
    date: "March 2025",
    slug: "/best-signboard-makers-wardha-road-nagpur",
    image: "/blog/Best Signboard Makers on Wardha Road Nagpur — Elevate Your Commercial Presence.png",
  },
];
